### ISSUE TITLE
No such method error on server

### ISSUE THREAD

**Issue by Sirse** [AnonymousProductions/MineFantasyII-Cont#2]
Calling of client-side only method getLocalisedName from ItemArrowMF class

http://pastebin.com/tpsB84CE

**Comment by AnonymousProductions** [comment]
Yeh same as another problem seen. Just servers being servers really..

Its to do with the tooltip above the crafting metre finding what the recipe is called.

**Comment by AnonymousProductions** [comment]
I just removed the Client-only setting, because names are still used on servers I guess, easier that way.
