### ISSUE TITLE
[Server]Costing too much bandwidth.

### ISSUE THREAD

**Issue by Yesterday17** [AnonymousProductions/MineFantasyII-Cont#9]
The problem is also commited on [CurseForge](https://minecraft.curseforge.com/projects/minefantasy2/issues/30).

According to the test, this mod has cost too much bandwidth. It's 3M in our server, and it's a greatly lagged if the number of players has reached 7.
After removing this mod, the usage of network was one fourth to the original usage.
I can offer **pcapng** file of wireshark if it's needed to help solve the problem. Hope it to be solved soon!

**Comment by Sirse** [comment]
Some MF stuff are implemented really dirty (e.g.: constant anvil sync) and need rewrite.
Please, attach wireshark dump (also, OPIS log, if you can).

**Comment by Yesterday17** [comment]
@Sirse Here is the wireshark dump. I've uploaded it to [onedrive](https://1drv.ms/u/s!Aof9Y87fPp4thGHPQq93ncy_N8lt).

**Comment by Sirse** [comment]
@yesterday17, thx, i'm will look it little bit later

**Comment by Sirse** [comment]
@yesterday17, please, try that build (this is zip package, unzip it, GitHub don't allow upload jar files directly).
[MineFantasyII-2.8.13.1u.zip](https://github.com/AnonymousProductions/MineFantasyII-Cont/files/1234957/MineFantasyII-2.8.13.1u.zip)
Only TEFirepit changed, but they are bugged in default version (they syncs before every tick, now they syncs only on condition change). I will rewrite constant sync of other TEs later.

**Comment by Yesterday17** [comment]
@Sirse ok, we'll test it on server~
